sim_hrs: 30
template_dir: /glade/u//home/ljaeger/wrf-run/templates/fire_21458836
wps_ins_dir: /glade/u/home/ljaeger/wrf-run/bin/WPS-4.6-dmpar-casper
wrf_ins_dir: /glade/u/home/ljaeger/wrf-run/bin/WRF-4.6
wps_run_dir: /glade/derecho/scratch/ljaeger/workflow/fire_21458836/wps
wrf_run_dir: /glade/derecho/scratch/ljaeger/workflow/fire_21458836/wrf
grib_dir: /glade/derecho/scratch/ljaeger/data/hrrr/fire_21458836
ungrib_domain: full
icbc_model: HRRR
icbc_source: AWS
icbc_fc_dt: 0
icbc_analysis: true
hrrr_native: true
get_icbc: false
do_geogrid: false
do_ungrib: false
do_avg_tsfc: false
use_tavgsfc: false
do_metgrid: false
do_real: false
do_wrf: true
archive: false
