sim_hrs: 30
template_dir: /glade/u//home/ljaeger/wrf-run/templates/fire_24462243
wps_ins_dir: /glade/u/home/ljaeger/wrf-run/bin/WPS-4.6-dmpar-casper
wrf_ins_dir: /glade/u/home/ljaeger/wrf-run/bin/WRF-4.6
wps_run_dir: /glade/derecho/scratch/ljaeger/workflow/fire_24462243/wps
wrf_run_dir: /glade/derecho/scratch/ljaeger/workflow/fire_24462243/wrf
grib_dir: /glade/derecho/scratch/ljaeger/data/hrrr/fire_24462243
ungrib_domain: full
icbc_model: HRRR
icbc_source: AWS
icbc_fc_dt: 0
icbc_analysis: true
hrrr_native: true
get_icbc: true
do_geogrid: true
do_ungrib: true
do_avg_tsfc: true
use_tavgsfc: true
do_metgrid: true
do_real: true
do_wrf: true
archive: false
